
CondaError: Run 'conda init' before 'conda activate'

/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
[node13:434728:0:434728] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
==== backtrace (tid: 434728) ====
 0  /opt/ohpc/pub/mpi/ucx-ohpc/1.11.2/lib/libucs.so.0(ucs_handle_error+0x254) [0x7f65d3466b94]
 1  /opt/ohpc/pub/mpi/ucx-ohpc/1.11.2/lib/libucs.so.0(+0x27d4c) [0x7f65d3466d4c]
 2  /opt/ohpc/pub/mpi/ucx-ohpc/1.11.2/lib/libucs.so.0(+0x27ff8) [0x7f65d3466ff8]
 3  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(numjac+0x573) [0x7f65c9c4f923]
 4  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(evolver_ndf15+0x55c) [0x7f65c9c5189c]
 5  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(background_solve+0x350) [0x7f65c9bb2f10]
 6  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(background_init+0x81) [0x7f65c9bb3ce1]
 7  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_try_unknown_parameters+0x289) [0x7f65c9ba9799]
 8  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_fzerofun_1d+0x29) [0x7f65c9baa3c9]
 9  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_fzero_ridder+0x2ed) [0x7f65c9b865ad]
10  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_find_root+0x22c) [0x7f65c9baa61c]
11  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_shooting+0xb6b) [0x7f65c9bab20b]
12  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_read_from_file+0x114) [0x7f65c9bab954]
13  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(+0xc1aee) [0x7f65c9b4daee]
14  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(+0xc52f5) [0x7f65c9b512f5]
15  /home/valerio/anaconda3/envs/vitor/bin/python(PyObject_Vectorcall+0x4f) [0x560fd01a3fcf]
16  /home/valerio/anaconda3/envs/vitor/bin/python(+0x113f65) [0x560fd0095f65]
17  /home/valerio/anaconda3/envs/vitor/bin/python(+0x25aeec) [0x560fd01dceec]
18  /home/valerio/anaconda3/envs/vitor/bin/python(+0x25a9fd) [0x560fd01dc9fd]
19  /home/valerio/anaconda3/envs/vitor/bin/python(_PyObject_Call+0x123) [0x560fd01c0353]
20  /home/valerio/anaconda3/envs/vitor/bin/python(+0x114ca6) [0x560fd0096ca6]
21  /home/valerio/anaconda3/envs/vitor/bin/python(PyEval_EvalCode+0xae) [0x560fd0249ece]
22  /home/valerio/anaconda3/envs/vitor/bin/python(+0x2ecd9a) [0x560fd026ed9a]
23  /home/valerio/anaconda3/envs/vitor/bin/python(+0x2e7f4b) [0x560fd0269f4b]
24  /home/valerio/anaconda3/envs/vitor/bin/python(+0x300bd0) [0x560fd0282bd0]
25  /home/valerio/anaconda3/envs/vitor/bin/python(_PyRun_SimpleFileObject+0x1be) [0x560fd028220e]
26  /home/valerio/anaconda3/envs/vitor/bin/python(_PyRun_AnyFileObject+0x44) [0x560fd0281ee4]
27  /home/valerio/anaconda3/envs/vitor/bin/python(Py_RunMain+0x2f2) [0x560fd027af42]
28  /home/valerio/anaconda3/envs/vitor/bin/python(Py_BytesMain+0x37) [0x560fd02327e7]
29  /lib64/libc.so.6(__libc_start_main+0xe5) [0x7f65ecb1cd85]
30  /home/valerio/anaconda3/envs/vitor/bin/python(+0x2b0681) [0x560fd0232681]
=================================
[node13:434728] *** Process received signal ***
[node13:434728] Signal: Segmentation fault (11)
[node13:434728] Signal code:  (-6)
[node13:434728] Failing at address: 0x3ed0006a228
[node13:434728] [ 0] /lib64/libpthread.so.0(+0x12cf0)[0x7f65ed643cf0]
[node13:434728] [ 1] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(numjac+0x573)[0x7f65c9c4f923]
[node13:434728] [ 2] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(evolver_ndf15+0x55c)[0x7f65c9c5189c]
[node13:434728] [ 3] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(background_solve+0x350)[0x7f65c9bb2f10]
[node13:434728] [ 4] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(background_init+0x81)[0x7f65c9bb3ce1]
[node13:434728] [ 5] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_try_unknown_parameters+0x289)[0x7f65c9ba9799]
[node13:434728] [ 6] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_fzerofun_1d+0x29)[0x7f65c9baa3c9]
[node13:434728] [ 7] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_fzero_ridder+0x2ed)[0x7f65c9b865ad]
[node13:434728] [ 8] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_find_root+0x22c)[0x7f65c9baa61c]
[node13:434728] [ 9] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_shooting+0xb6b)[0x7f65c9bab20b]
[node13:434728] [10] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_read_from_file+0x114)[0x7f65c9bab954]
[node13:434728] [11] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(+0xc1aee)[0x7f65c9b4daee]
[node13:434728] [12] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(+0xc52f5)[0x7f65c9b512f5]
[node13:434728] [13] /home/valerio/anaconda3/envs/vitor/bin/python(PyObject_Vectorcall+0x4f)[0x560fd01a3fcf]
[node13:434728] [14] /home/valerio/anaconda3/envs/vitor/bin/python(+0x113f65)[0x560fd0095f65]
[node13:434728] [15] /home/valerio/anaconda3/envs/vitor/bin/python(+0x25aeec)[0x560fd01dceec]
[node13:434728] [16] /home/valerio/anaconda3/envs/vitor/bin/python(+0x25a9fd)[0x560fd01dc9fd]
[node13:434728] [17] /home/valerio/anaconda3/envs/vitor/bin/python(_PyObject_Call+0x123)[0x560fd01c0353]
[node13:434728] [18] /home/valerio/anaconda3/envs/vitor/bin/python(+0x114ca6)[0x560fd0096ca6]
[node13:434728] [19] /home/valerio/anaconda3/envs/vitor/bin/python(PyEval_EvalCode+0xae)[0x560fd0249ece]
[node13:434728] [20] /home/valerio/anaconda3/envs/vitor/bin/python(+0x2ecd9a)[0x560fd026ed9a]
[node13:434728] [21] /home/valerio/anaconda3/envs/vitor/bin/python(+0x2e7f4b)[0x560fd0269f4b]
[node13:434728] [22] /home/valerio/anaconda3/envs/vitor/bin/python(+0x300bd0)[0x560fd0282bd0]
[node13:434728] [23] /home/valerio/anaconda3/envs/vitor/bin/python(_PyRun_SimpleFileObject+0x1be)[0x560fd028220e]
[node13:434728] [24] /home/valerio/anaconda3/envs/vitor/bin/python(_PyRun_AnyFileObject+0x44)[0x560fd0281ee4]
[node13:434728] [25] /home/valerio/anaconda3/envs/vitor/bin/python(Py_RunMain+0x2f2)[0x560fd027af42]
[node13:434728] [26] /home/valerio/anaconda3/envs/vitor/bin/python(Py_BytesMain+0x37)[0x560fd02327e7]
[node13:434728] [27] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f65ecb1cd85]
[node13:434728] [28] /home/valerio/anaconda3/envs/vitor/bin/python(+0x2b0681)[0x560fd0232681]
[node13:434728] *** End of error message ***
--------------------------------------------------------------------------
prterun noticed that process rank 0 with PID 434728 on node node13 exited on
signal 11 (Segmentation fault).
--------------------------------------------------------------------------

real	3m56.984s
user	11m1.294s
sys	0m6.825s
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
[node13:485188:0:485188] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
==== backtrace (tid: 485188) ====
 0  /opt/ohpc/pub/mpi/ucx-ohpc/1.11.2/lib/libucs.so.0(ucs_handle_error+0x254) [0x7f4a4403cb94]
 1  /opt/ohpc/pub/mpi/ucx-ohpc/1.11.2/lib/libucs.so.0(+0x27d4c) [0x7f4a4403cd4c]
 2  /opt/ohpc/pub/mpi/ucx-ohpc/1.11.2/lib/libucs.so.0(+0x27ff8) [0x7f4a4403cff8]
 3  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(numjac+0x573) [0x7f4a3a8e5923]
 4  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(evolver_ndf15+0x55c) [0x7f4a3a8e789c]
 5  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(background_solve+0x350) [0x7f4a3a848f10]
 6  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(background_init+0x81) [0x7f4a3a849ce1]
 7  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_try_unknown_parameters+0x289) [0x7f4a3a83f799]
 8  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_fzerofun_1d+0x29) [0x7f4a3a8403c9]
 9  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_find_root+0xb7) [0x7f4a3a8404a7]
10  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_shooting+0xb6b) [0x7f4a3a84120b]
11  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_read_from_file+0x114) [0x7f4a3a841954]
12  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(+0xc1aee) [0x7f4a3a7e3aee]
13  /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(+0xc52f5) [0x7f4a3a7e72f5]
14  /home/valerio/anaconda3/envs/vitor/bin/python(PyObject_Vectorcall+0x4f) [0x5556ab54cfcf]
15  /home/valerio/anaconda3/envs/vitor/bin/python(+0x113f65) [0x5556ab43ef65]
16  /home/valerio/anaconda3/envs/vitor/bin/python(+0x25aeec) [0x5556ab585eec]
17  /home/valerio/anaconda3/envs/vitor/bin/python(+0x25a9fd) [0x5556ab5859fd]
18  /home/valerio/anaconda3/envs/vitor/bin/python(_PyObject_Call+0x123) [0x5556ab569353]
19  /home/valerio/anaconda3/envs/vitor/bin/python(+0x114ca6) [0x5556ab43fca6]
20  /home/valerio/anaconda3/envs/vitor/bin/python(PyEval_EvalCode+0xae) [0x5556ab5f2ece]
21  /home/valerio/anaconda3/envs/vitor/bin/python(+0x2ecd9a) [0x5556ab617d9a]
22  /home/valerio/anaconda3/envs/vitor/bin/python(+0x2e7f4b) [0x5556ab612f4b]
23  /home/valerio/anaconda3/envs/vitor/bin/python(+0x300bd0) [0x5556ab62bbd0]
24  /home/valerio/anaconda3/envs/vitor/bin/python(_PyRun_SimpleFileObject+0x1be) [0x5556ab62b20e]
25  /home/valerio/anaconda3/envs/vitor/bin/python(_PyRun_AnyFileObject+0x44) [0x5556ab62aee4]
26  /home/valerio/anaconda3/envs/vitor/bin/python(Py_RunMain+0x2f2) [0x5556ab623f42]
27  /home/valerio/anaconda3/envs/vitor/bin/python(Py_BytesMain+0x37) [0x5556ab5db7e7]
28  /lib64/libc.so.6(__libc_start_main+0xe5) [0x7f4a5d6f2d85]
29  /home/valerio/anaconda3/envs/vitor/bin/python(+0x2b0681) [0x5556ab5db681]
=================================
[node13:485188] *** Process received signal ***
[node13:485188] Signal: Segmentation fault (11)
[node13:485188] Signal code:  (-6)
[node13:485188] Failing at address: 0x3ed00076744
[node13:485188] [ 0] /lib64/libpthread.so.0(+0x12cf0)[0x7f4a5e219cf0]
[node13:485188] [ 1] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(numjac+0x573)[0x7f4a3a8e5923]
[node13:485188] [ 2] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(evolver_ndf15+0x55c)[0x7f4a3a8e789c]
[node13:485188] [ 3] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(background_solve+0x350)[0x7f4a3a848f10]
[node13:485188] [ 4] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(background_init+0x81)[0x7f4a3a849ce1]
[node13:485188] [ 5] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_try_unknown_parameters+0x289)[0x7f4a3a83f799]
[node13:485188] [ 6] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_fzerofun_1d+0x29)[0x7f4a3a8403c9]
[node13:485188] [ 7] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_find_root+0xb7)[0x7f4a3a8404a7]
[node13:485188] [ 8] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_shooting+0xb6b)[0x7f4a3a84120b]
[node13:485188] [ 9] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(input_read_from_file+0x114)[0x7f4a3a841954]
[node13:485188] [10] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(+0xc1aee)[0x7f4a3a7e3aee]
[node13:485188] [11] /home/valerio/Vitor/cobaya/class/build/lib.linux-x86_64-cpython-312/classy.cpython-312-x86_64-linux-gnu.so(+0xc52f5)[0x7f4a3a7e72f5]
[node13:485188] [12] /home/valerio/anaconda3/envs/vitor/bin/python(PyObject_Vectorcall+0x4f)[0x5556ab54cfcf]
[node13:485188] [13] /home/valerio/anaconda3/envs/vitor/bin/python(+0x113f65)[0x5556ab43ef65]
[node13:485188] [14] /home/valerio/anaconda3/envs/vitor/bin/python(+0x25aeec)[0x5556ab585eec]
[node13:485188] [15] /home/valerio/anaconda3/envs/vitor/bin/python(+0x25a9fd)[0x5556ab5859fd]
[node13:485188] [16] /home/valerio/anaconda3/envs/vitor/bin/python(_PyObject_Call+0x123)[0x5556ab569353]
[node13:485188] [17] /home/valerio/anaconda3/envs/vitor/bin/python(+0x114ca6)[0x5556ab43fca6]
[node13:485188] [18] /home/valerio/anaconda3/envs/vitor/bin/python(PyEval_EvalCode+0xae)[0x5556ab5f2ece]
[node13:485188] [19] /home/valerio/anaconda3/envs/vitor/bin/python(+0x2ecd9a)[0x5556ab617d9a]
[node13:485188] [20] /home/valerio/anaconda3/envs/vitor/bin/python(+0x2e7f4b)[0x5556ab612f4b]
[node13:485188] [21] /home/valerio/anaconda3/envs/vitor/bin/python(+0x300bd0)[0x5556ab62bbd0]
[node13:485188] [22] /home/valerio/anaconda3/envs/vitor/bin/python(_PyRun_SimpleFileObject+0x1be)[0x5556ab62b20e]
[node13:485188] [23] /home/valerio/anaconda3/envs/vitor/bin/python(_PyRun_AnyFileObject+0x44)[0x5556ab62aee4]
[node13:485188] [24] /home/valerio/anaconda3/envs/vitor/bin/python(Py_RunMain+0x2f2)[0x5556ab623f42]
[node13:485188] [25] /home/valerio/anaconda3/envs/vitor/bin/python(Py_BytesMain+0x37)[0x5556ab5db7e7]
[node13:485188] [26] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f4a5d6f2d85]
[node13:485188] [27] /home/valerio/anaconda3/envs/vitor/bin/python(+0x2b0681)[0x5556ab5db681]
[node13:485188] *** End of error message ***
--------------------------------------------------------------------------
prterun noticed that process rank 1 with PID 485188 on node node13 exited on
signal 11 (Segmentation fault).
--------------------------------------------------------------------------

real	884m47.114s
user	2658m9.067s
sys	15m56.796s
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")
/home/valerio/anaconda3/envs/vitor/lib/python3.12/site-packages/act_dr6_lenslike/act_dr6_lenslike.py:422: UserWarning: Hartlap correction to cinv: 0.9860935524652339
  warnings.warn(f"Hartlap correction to cinv: {hartlap_correction}")

real	2170m30.132s
user	8504m7.977s
sys	48m55.162s
